name: Build MariaDB 11.8-Standard

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout MariaDB Source
        uses: actions/checkout@v4
        with:
          repository: MariaDB/server
          # ref: mariadb-11.8.9
          ref: bf9193a939f515e95dd8def1a5468088c91cede6
          submodules: recursive

      - name: Install Bison and Flex
        run: choco install winflexbison3

      - name: Setup MSVC Compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        run: |
          cmake -B build -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_CONFIG=mysql_release `
            -DWITH_EMBEDDED_SERVER=ON `
            -DCMAKE_INSTALL_PREFIX=build/redist

      - name: Build MariaDB
        run: cmake --build build

      - name: Install Files to Redist Folder
        run: cmake --install build

      - name: Compress Redistributable Package
        run: |
          Compress-Archive -Path build/redist/* -DestinationPath mariadb-11.8.9-standard.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mariadb-11.8.9-standard
          path: mariadb-11.8.9-standard.zip