name: Build MariaDB 11.8-CPack

on:
  workflow_dispatch: # Abilita l'avvio manuale

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout MariaDB Source
        uses: actions/checkout@v4
        with:
          repository: MariaDB/server
          ref: mariadb-11.8.9
          submodules: recursive

      - name: Install Bison and Flex
        run: choco install winflexbison3        

      - name: Setup MSVC Compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: |
          cmake -B build -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_CONFIG=mysql_release `
            -DWITH_EMBEDDED_SERVER=ON `
            -DWITH_UNIT_TESTS=OFF `
            -DNOT_WITH_MTR=ON `
            -DINSTALL_NOSYMBOLS=ON `
            -DCPACK_NOSYMBOLS=ON `
            -DWITH_GSSAPI=OFF `
            -DINSTALL_DOCDIR=NONE `
            -DINSTALL_DOCREADMEDIR=NONE `
            -DINSTALL_SUPPORTFILESDIR=NONE `
            -DWITH_MARIABACKUP=OFF `
            -DWITH_WSREP=OFF `
            -DPLUGIN_MYISAM=NO `
            -DPLUGIN_ARIA=YES `
            -DPLUGIN_INNOBASE=YES `
            -DPLUGIN_ARCHIVE=NO `
            -DPLUGIN_BLACKHOLE=NO `
            -DPLUGIN_CSV=NO `
            -DPLUGIN_FEDERATEDX=NO `
            -DPLUGIN_ROCKSDB=NO `
            -DPLUGIN_CONNECT=NO `
            -DPLUGIN_SEQUENCE=NO `
            -DPLUGIN_SPIDER=NO

      - name: Build Embedded Server
        run: cmake --build build --target all

      - name: Run CPack Packaging
        working-directory: ./build
        run: cpack -G ZIP # Genera un file .zip nativo pulito per Windows (usa TGZ su Linux)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mariadb-11.8.9-custom-winx64
          path: build/*.zip
